# data params
# dataset: '3_core'
num_workers: 30

# model params
model: 'MTER'
model_type: 'tag_aware'
u_emb_size: 16
i_emb_size: 16
t_emb_size: 16

# run params
rating_weight: 1
pos_aspect_weight: 1
neg_aspect_weight: 1
l2_weight: 0.0001
non_neg_weight: 0.1
lr: 0.01
learner: 'adam'
weight_decay: 0
epochs: 100
batch_size: 256
top_k: 10
neg_sample_num: 1
endure_times: 3
train_type: 'bpr'
rating_train_type: 'mse'
candidate_num: 100
tagset_num: 2

main_log_dir: './tensorboard_logs'

# general params
seed: 1111
cuda: True
gpu_id: 0
checkpoint: './checkpoints/mter_2tag_mse'